In [19]:
import  numpy as np 
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([0,0,0,1])
w = np.zeros(X.shape[1])
b = 0.0
lerning_rate = 1.0
for epoch  in  range(10): 
    for x , target in  zip(X,y):
        z = np.dot(x, w) + b
        prediction = 1 if z >= 0 else 0
        error =  target - prediction

        w = w + lerning_rate * error * x
        b = b + lerning_rate * error
        print(z)
    print("--------------------")
    print(
        "Epoch:", epoch + 1,
        "Weights:", w,
        "Bias:", b
    )  

0.0
-1.0
-1.0
-1.0
--------------------
Epoch: 1 Weights: [1. 1.] Bias: 0.0
0.0
0.0
-1.0
-1.0
--------------------
Epoch: 2 Weights: [2. 1.] Bias: -1.0
-1.0
0.0
0.0
-2.0
--------------------
Epoch: 3 Weights: [2. 1.] Bias: -2.0
-2.0
-1.0
0.0
-1.0
--------------------
Epoch: 4 Weights: [2. 2.] Bias: -2.0
-2.0
0.0
-1.0
0.0
--------------------
Epoch: 5 Weights: [2. 1.] Bias: -3.0
-3.0
-2.0
-1.0
0.0
--------------------
Epoch: 6 Weights: [2. 1.] Bias: -3.0
-3.0
-2.0
-1.0
0.0
--------------------
Epoch: 7 Weights: [2. 1.] Bias: -3.0
-3.0
-2.0
-1.0
0.0
--------------------
Epoch: 8 Weights: [2. 1.] Bias: -3.0
-3.0
-2.0
-1.0
0.0
--------------------
Epoch: 9 Weights: [2. 1.] Bias: -3.0
-3.0
-2.0
-1.0
0.0
--------------------
Epoch: 10 Weights: [2. 1.] Bias: -3.0


In [34]:
class Perceptron: 
    def __init__(self, learning_rate = 1.0,  epochs = 10 ):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias =  0.0 

    def fit(self, X, y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0.0
        for epoch  in  range(self.epochs):
            for x , target in  zip(X, y):
                z = np.dot(x, self.weights) + self.bias
                prediction = 1 if z >= 0 else 0 
                error = target - prediction
                self.weights += self.learning_rate * error * x
                self.bias += self.learning_rate * error
        return self

    def predict(self , X):
        z = X @ self.weights + self.bias
        return (z >= 0).astype(int)

In [ ]:
import numpy as np

class Perceptron:

    def __init__(self, learning_rate=1.0, epochs=10):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = 0.0

    def fit(self, X, y):

        self.weights = np.zeros(X.shape[1])
        self.bias = 0.0

        for epoch in range(self.epochs):

            for x, target in zip(X, y):

                z = np.dot(x, self.weights) + self.bias

                prediction = 1 if z >= 0 else 0

                error = target - prediction

                self.weights += self.lr * error * x
                self.bias += self.lr * error

        return self

    def predict(self, X):

        z = X @ self.weights + self.bias

        return (z >= 0).astype(int)

In [36]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([0, 0, 0, 1])
model = Perceptron(
    learning_rate=1.0,
    epochs=10
)
model.fit(X, y)
print("Weights:", model.weights)
print("Bias:", model.bias)
print("Predictions:", model.predict(X))

Weights: [2. 1.]
Bias: -3.0
Predictions: [0 0 0 1]


In [46]:
a = np.array([[1,2],
             [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]])
for i in a:
    print(i.shape)
print(np.argmax([1,5,73,200,5]))

(2,)
(2,)
(2,)
(2,)
(2,)
3


In [47]:
class PercetronMultiClass:
    def __init__(self, learning_rate = 1.0,  epochs = 10, no_classes = None):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None
        self.no_classes = no_classes

    def fit(self, X, y):
        
        self.weights = np.zeros((self.no_classes, X.shape[1]))
        self.bias = np.zeros( self.no_classes)

        for epoch in  range(self.epochs):
            for x, target in  zip(X, y):
                z = self.weights @ x + b 
                prediction = np.argmax(z)

                if prediction != target:
                    self.weights[target] += self.learning_rate * x
                    self.bias[target] += self.learning_rate

                    self.weights[prediction] -= self.learning_rate * x
                    self.bias[prediction] -= self.learning_rate       

In [49]:
import numpy as np

class MulticlassPerceptron:

    def __init__(self, learning_rate=1.0, epochs=10):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None

    def fit(self, X, y):

        n_samples, n_features = X.shape
        n_classes = len(np.unique(y))

        self.weights = np.zeros((n_classes, n_features))
        self.bias = np.zeros(n_classes)

        for epoch in range(self.epochs):

            for x, target in zip(X, y):

                z = self.weights @ x + self.bias

                prediction = np.argmax(z)

                if prediction != target:

                    self.weights[target] += self.learning_rate * x
                    self.bias[target] += self.learning_rate

                    self.weights[prediction] -= self.learning_rate * x
                    self.bias[prediction] -= self.learning_rate

        return self

    def predict(self, X):

        z = X @ self.weights.T + self.bias

        return np.argmax(z, axis=1)

    def score(self, X, y):

        predictions = self.predict(X)

        return np.mean(predictions == y)

In [51]:
X = np.array([
    [2, 1],
    [1, 3],
    [3, 2]
], dtype=float)

y = np.array([0, 1, 2])

model = MulticlassPerceptron(
    learning_rate=1.0,
    epochs=10
)
model.fit(X, y)
predictions = model.predict(X)

print(predictions)

[0 1 2]


In [63]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder, StandardScaler
from  sklearn.model_selection import train_test_split

label_encoders = LabelEncoder()
scaler = StandardScaler()

df = pd.read_csv('../__train_dataset__/Data_fruit.csv')
X = df.drop("Class", axis=1)
y = df['Class']

y_encoder = label_encoders.fit_transform(y)

X_train,  X_test ,y_train, y_test = train_test_split(X, y_encoder , test_size=0.2,  random_state=42)

X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

model = MulticlassPerceptron(learning_rate=1.0,  epochs=100)

model = MulticlassPerceptron(
    learning_rate=1.0,
    epochs=100
)

model.fit(X_train_scaler, y_train)

print("Weights shape:", model.weights.shape)
print("Bias shape:", model.bias.shape)

predictions = model.predict(X_test_scaler)

print("Predictions:", predictions)

accuracy = model.score(X_test_scaler, y_test)

print("Accuracy:", accuracy)
print("Accuracy:", accuracy * 100, "%")


Weights shape: (7, 34)
Bias shape: (7,)
Predictions: [2 5 2 6 0 2 3 2 2 1 1 2 2 2 4 4 1 5 6 1 5 4 2 0 5 2 3 6 0 5 6 2 2 4 2 5 0
 1 2 5 1 4 5 5 1 1 1 2 2 5 4 3 2 6 2 4 6 2 2 0 3 6 2 2 2 1 1 2 4 6 2 2 4 1
 3 4 2 4 5 4 2 1 4 3 2 4 2 5 3 2 2 5 5 3 1 2 1 2 2 4 4 3 2 5 5 4 3 4 4 2 5
 2 4 4 4 1 1 5 5 4 4 2 5 1 5 5 1 1 4 4 2 1 3 4 4 1 4 2 5 0 5 5 5 1 6 5 2 0
 0 5 6 4 6 1 6 5 6 1 2 3 5 2 6 5 0 0 2 3 2 4 1 6 5 6 1 5 0 1 0 1]
Accuracy: 0.8888888888888888
Accuracy: 88.88888888888889 %


In [62]:
print(np.unique(y_encoder))
print(np.unique(y_train))
print(len(np.unique(y_encoder)))
print(X_train_scaler.shape)
print(y_train.shape)

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]
7
(718, 34)
(718,)


In [66]:
print(np.mean([True,False,True]))
print(2/3)

0.6666666666666666
0.6666666666666666
