In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

import tensorflow as tf
from torch.utils.data import TensorDataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [ ]:
fruit_data = pd.read_csv('https://raw.githubusercontent.com/vishwa-Ansh/DataLoaders/refs/heads/main/Data_fruit.csv')
fruit_data

In [5]:
X = fruit_data.drop('Class', axis=1)
y = fruit_data['Class']


label_encoding  = LabelEncoder()
y = label_encoding.fit_transform(y)

X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_test.shape, y_test.shape)
print(X_train.shape, y_train.shape)

scaler_encoding = StandardScaler()
X_train_scale = scaler_encoding.fit_transform(X_train)
X_test_scale = scaler_encoding.transform(X_test)

X_train_tensor = torch.tensor(X_train_scale, dtype = torch.float32)
X_test_tensor =  torch.tensor(X_test_scale, dtype = torch.float32)

y_train_tensor = torch.tensor(y_train,  dtype = torch.long)
y_test_tensor = torch.tensor(y_test,  dtype=torch.long)
print(X_test_tensor)
print(y_train_tensor)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor,  y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle= False)

(180, 34) (180,)
(718, 34) (718,)
tensor([[-1.4681, -1.5104, -1.6110,  ...,  1.7157,  1.8864,  1.3899],
        [-0.3808, -0.2304,  0.0503,  ..., -2.0761, -1.8388, -1.7477],
        [-1.3722, -1.3848, -1.4493,  ..., -0.0923, -0.1138, -0.1319],
        ...,
        [-0.4487, -0.2655, -0.1040,  ...,  0.9154,  0.9146,  0.9736],
        [ 0.5883,  0.3596,  0.2474,  ...,  0.1883,  0.3185,  0.2283],
        [-1.3555, -1.2297, -1.1075,  ...,  1.3047,  1.6137,  1.4415]])
tensor([6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4, 5, 4, 6, 6, 4, 2,
        5, 5, 5, 4, 4, 2, 4, 6, 5, 6, 2, 0, 5, 1, 4, 3, 1, 2, 6, 2, 2, 3, 2, 5,
        2, 4, 0, 2, 6, 4, 2, 1, 4, 6, 5, 5, 5, 5, 3, 4, 3, 4, 3, 6, 5, 2, 4, 1,
        1, 3, 0, 3, 3, 4, 6, 2, 1, 4, 4, 5, 4, 5, 6, 2, 3, 5, 2, 2, 4, 6, 2, 6,
        1, 6, 2, 5, 5, 1, 1, 3, 6, 1, 2, 0, 4, 2, 2, 4, 4, 3, 1, 2, 0, 4, 4, 1,
        5, 3, 5, 1, 2, 2, 5, 3, 1, 4, 4, 2, 0, 4, 1, 3, 0, 2, 4, 6, 0, 2, 3, 3,
        0, 3, 6, 5, 2, 4, 5, 3, 5, 0, 5, 4, 1, 0, 2,

In [6]:
y_train

array([6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4, 5, 4, 6, 6,
       4, 2, 5, 5, 5, 4, 4, 2, 4, 6, 5, 6, 2, 0, 5, 1, 4, 3, 1, 2, 6, 2,
       2, 3, 2, 5, 2, 4, 0, 2, 6, 4, 2, 1, 4, 6, 5, 5, 5, 5, 3, 4, 3, 4,
       3, 6, 5, 2, 4, 1, 1, 3, 0, 3, 3, 4, 6, 2, 1, 4, 4, 5, 4, 5, 6, 2,
       3, 5, 2, 2, 4, 6, 2, 6, 1, 6, 2, 5, 5, 1, 1, 3, 6, 1, 2, 0, 4, 2,
       2, 4, 4, 3, 1, 2, 0, 4, 4, 1, 5, 3, 5, 1, 2, 2, 5, 3, 1, 4, 4, 2,
       0, 4, 1, 3, 0, 2, 4, 6, 0, 2, 3, 3, 0, 3, 6, 5, 2, 4, 5, 3, 5, 0,
       5, 4, 1, 0, 2, 2, 2, 5, 0, 2, 4, 4, 2, 4, 5, 5, 3, 4, 4, 2, 4, 5,
       2, 2, 4, 5, 1, 1, 4, 5, 1, 1, 4, 1, 4, 1, 2, 6, 6, 6, 4, 5, 1, 0,
       3, 0, 0, 2, 2, 5, 4, 5, 4, 2, 4, 5, 4, 2, 5, 5, 5, 3, 2, 4, 2, 5,
       0, 0, 3, 2, 4, 6, 5, 3, 2, 6, 6, 5, 2, 4, 0, 2, 0, 2, 2, 4, 5, 6,
       4, 2, 6, 4, 2, 2, 1, 4, 4, 6, 2, 2, 5, 3, 4, 1, 1, 5, 4, 2, 1, 6,
       2, 2, 5, 4, 2, 1, 5, 1, 1, 5, 2, 2, 0, 6, 4, 5, 3, 4, 1, 2, 5, 1,
       2, 5, 5, 4, 4, 2, 2, 5, 1, 5, 6, 6, 5, 3, 2,

In [7]:
X_train = np.asarray(X_train_scale, dtype=np.float32)
X_test = np.asarray(X_test_scale, dtype=np.float32)

y_train = np.asarray(y_train, dtype=np.int32)
y_test = np.asarray(y_test, dtype=np.int32)

model = tf.keras.Sequential([
    tf.keras.layers.Input(
        shape=(X_train.shape[1],)
    ),

    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(7)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(
         learning_rate=0.001
    ),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True
    ),
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

logits = model.predict(X_test)

probabilities = tf.nn.softmax(
    logits,
    axis=1
)

print("Probabilities:")
print(probabilities.numpy())

predictions = tf.argmax(
    probabilities,
    axis=1
)

print("Predicted classes:")
print(predictions.numpy())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu (ReLU)                    │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_1 (ReLU)                  │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 7)              │           231 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,407 (9.40 KB)

 Trainable params: 2,407 (9.40 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.2439 - loss: 1.8142 - val_accuracy: 0.4583 - val_loss: 1.5328
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5697 - loss: 1.3509 - val_accuracy: 0.6944 - val_loss: 1.1747
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6760 - loss: 1.0561 - val_accuracy: 0.6944 - val_loss: 0.9445
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7038 - loss: 0.8703 - val_accuracy: 0.7361 - val_loss: 0.7865
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7369 - loss: 0.7463 - val_accuracy: 0.7708 - val_loss: 0.6784
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7613 - loss: 0.6579 - val_accuracy: 0.7986 - val_loss: 0.5964
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7875 - loss: 0.5863 - val_accuracy: 0.8333 - val_loss: 0.5263
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8171 - loss: 0.5276 - val_accuracy: 0.8403 - 

In [8]:
X_train_tensorflow = np.asarray(X_train_scale, dtype=np.float32)
X_test_tensorflow = np.asarray(X_test_scale, dtype=np.float32
                                )

y_train_tensorflow = np.asarray(y_train, dtype=np.int32)
y_test_tensorflow = np.asarray(y_test, dtype=np.int32)


In [11]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(
        shape=(X_train_tensorflow.shape[1],)
    ),
    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(32),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(7)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(
         learning_rate=0.001
    ),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True
    ),
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    X_train_tensorflow,
    y_train_tensorflow,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(
    X_test_tensorflow,
    y_test_tensorflow
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_4 (ReLU)                  │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_5 (ReLU)                  │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 7)              │           231 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,407 (9.40 KB)

 Trainable params: 2,407 (9.40 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - accuracy: 0.3606 - loss: 1.6975 - val_accuracy: 0.5347 - val_loss: 1.4780
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5470 - loss: 1.2721 - val_accuracy: 0.6319 - val_loss: 1.1772
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6934 - loss: 1.0328 - val_accuracy: 0.7014 - val_loss: 0.9804
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7195 - loss: 0.8691 - val_accuracy: 0.7222 - val_loss: 0.8066
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7213 - loss: 0.7258 - val_accuracy: 0.7569 - val_loss: 0.6717
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7578 - loss: 0.6278 - val_accuracy: 0.7917 - val_loss: 0.5747
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7805 - loss: 0.5525 - val_accuracy: 0.8472 - val_loss: 0.5104
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8066 - loss: 0.4998 - val_accuracy: 0.

In [15]:
X_train_tensor = torch.tensor(X_train_scale, dtype = torch.float32)
X_test_tensor =  torch.tensor(X_test_scale, dtype = torch.float32)

y_train_tensor = torch.tensor(y_train,  dtype = torch.long)
y_test_tensor = torch.tensor(y_test,  dtype=torch.long)
print(X_test_tensor)
print(y_train_tensor)

trianDataset = TensorDataset(X_train_tensor, y_train_tensor)
testDataset = TensorDataset(X_test_tensor,  y_test_tensor)

train_loader = DataLoader(trianDataset, batch_size=32, shuffle=True)
test_loader = DataLoader(testDataset, batch_size = 32, shuffle= False)

class Artificial_neural_network(nn.Module):
    def __init__(self):
        super(Artificial_neural_network, self).__init__()
        self.input_layer = nn.Linear(X_train_tensor.shape[1], 32)
        self.hidden_layer1 = nn.Linear(32, 32)
        self.output_layer = nn.Linear(32, 7)
        self.relu = nn.ReLU()
    def forward(self, x):
        x = self.input_layer(x)
        x = self.relu(x)
        x = self.hidden_layer1(x)
        x = self.relu(x)
        x = self.output_layer(x)
        return x

epochs = 100
learning_rate = 0.001

model = Artificial_neural_network()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
  running_loss = 0.0
  model.train();
  for batch_idx, (data, target) in enumerate(train_loader):
    optimizer.zero_grad()
    output = model(data)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  train_loss = running_loss / len(train_loader)
  print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")



model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb) # [0.2, 0.5, 1.3, -0.5, ..] - 7 vals
        _values, indices = torch.max(outputs, dim=1)
        print(indices )
        # print(outputs)
        correct += (indices == yb).sum().item()
        total += yb.size(0) # actual samples in each batch

print("accuracy: ", correct/total * 100)
# print(accuracy_score())

tensor([[-1.4681, -1.5104, -1.6110,  ...,  1.7157,  1.8864,  1.3899],
        [-0.3808, -0.2304,  0.0503,  ..., -2.0761, -1.8388, -1.7477],
        [-1.3722, -1.3848, -1.4493,  ..., -0.0923, -0.1138, -0.1319],
        ...,
        [-0.4487, -0.2655, -0.1040,  ...,  0.9154,  0.9146,  0.9736],
        [ 0.5883,  0.3596,  0.2474,  ...,  0.1883,  0.3185,  0.2283],
        [-1.3555, -1.2297, -1.1075,  ...,  1.3047,  1.6137,  1.4415]])
tensor([6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4, 5, 4, 6, 6, 4, 2,
        5, 5, 5, 4, 4, 2, 4, 6, 5, 6, 2, 0, 5, 1, 4, 3, 1, 2, 6, 2, 2, 3, 2, 5,
        2, 4, 0, 2, 6, 4, 2, 1, 4, 6, 5, 5, 5, 5, 3, 4, 3, 4, 3, 6, 5, 2, 4, 1,
        1, 3, 0, 3, 3, 4, 6, 2, 1, 4, 4, 5, 4, 5, 6, 2, 3, 5, 2, 2, 4, 6, 2, 6,
        1, 6, 2, 5, 5, 1, 1, 3, 6, 1, 2, 0, 4, 2, 2, 4, 4, 3, 1, 2, 0, 4, 4, 1,
        5, 3, 5, 1, 2, 2, 5, 3, 1, 4, 4, 2, 0, 4, 1, 3, 0, 2, 4, 6, 0, 2, 3, 3,
        0, 3, 6, 5, 2, 4, 5, 3, 5, 0, 5, 4, 1, 0, 2, 2, 2, 5, 0, 2, 4, 4, 2, 4,
      